apiVersion: v1
kind: Service
metadata:
  name: resource-fetcher
  namespace: resource-fetcher-namespace
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: resource-fetcher-pls
spec:
  type: LoadBalancer
  ports:
  - port: 6072
  selector:
    app: resource-fetcher