solutionInfo:
  aksClusterName: rfinteusaks
  environment: INT
  region: eastus

# use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
resourceFetcherServiceAccount:
  # Replace Client Id with MI's Client Id
  clientId: 66db9ecf-dbb3-4586-bfd1-7ab04c903106 #79591dff-d30a-4bfb-8eb1-1a8b7bdc2656
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47

resourceFetcherService:
  replicaCount: 1    
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
  aadTokenIssuer: https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/
  aadTokenAudience: https://resourcefetcherservice-int.microsoft.com
# ARM Client Related
  armClient:
    firstPartyAppId: e6a18a18-ffe6-4ac3-b822-362bb577a6a3
    certificateName: aad-rp-int-arg-first-party-app-cert
 # Cas Client Related
  casClient:
    endpoints: https://capacity-usnorth-test.northcentralus.cloudapp.azure.com
    certificateName: datalabs-dsts-client-int-gov-rp-art-int
    # Cas test endpoint doesnt have a valid certificate yet
    dstsSkipServerCertificateValidation: true
    dstsClientId: c1c8a0fd-eba8-4c02-add2-d6b1ec35dd52
    dstsServerId: b559514b-96c3-45e5-8469-25d2e6e0bc7e
    dstsClientHome: https://co2agg04-passive-dsts.dsts.core.azure-test.net/dstsv2/7a433bfc-2514-4697-b467-e0933190487f
    dstsServerHome: ""
    dstsServerRealm: ""
# ARG Query FrontDoor Client Related
  qfdClient:
    endpoints: https://arg-df-qfd.arg-df.core.windows.net
    certificateName: datalabs-dsts-client-int-gov-rp-art-int
    dstsSkipServerCertificateValidation: false
    dstsClientId: c1c8a0fd-eba8-4c02-add2-d6b1ec35dd52
    dstsServerId: 5a5b6d3c-f6cb-4570-95be-059ab813a8ff
    dstsClientHome: https://co2agg04-passive-dsts.dsts.core.azure-test.net/dstsv2/7a433bfc-2514-4697-b467-e0933190487f
    dstsServerHome: ""
    dstsServerRealm: ""
# ARM Admin Client Related
  armAdminClient:
    endpoints: https://northeurope.api-dogfood-admin.resources.windows-int.net
    certificateName: datalabs-arm-admin-int-gov-rp-art-int

keyVault:
  name: datalabsintgblkv
  clientId: 9e7927ef-b813-490b-a71e-8cefc1fdfd2f #skucluster #b46b5c00-d893-42df-b0eb-aae2203bfa97 eug-datalabs #this needs to be VMSS kubelet identity or else causes errors
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
  
resourceFetcherConfigMap:
  partnerNames: "sku"    # this should match with Partner AKS value file's solution name (solutionInfo -> solutionName)

skuConfigMap:
  clientIds: 79591dff-d30a-4bfb-8eb1-1a8b7bdc2656

resourceFetcherImage:
  repository: armdataacrskudfeastus.azurecr.io/resourcefetcherservice
  tag: dstsarmadmin

# Monitoring configurations
monitorInfo:
  name: geneva-services
  updateStrategy: RollingUpdate
  hostNetwork: true
  exporterType: GENEVA # default is console exporter

genevaAccounts:
  datalabs:
    gcs_environment: Test
    gcs_account: DataLabs
    gcs_region: eastus
    gcs_namespace: DataLabs
    gcs_config_version: "1.5" 
    miResourceId: /subscriptions/02d59989-f8a9-4b69-9919-1ef51df4eff6/resourcegroups/MC_DataLabsRFRG-eastus_rfinteusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rfinteusaks-agentpool

mdm:
  containerName: mdm
  repository: linuxgeneva-microsoft.azurecr.io/distroless/genevamdm
  tag: 2.2023.210.1608-70acef-20230210t1718

  # Input types
  mdm_input: ifx_local,ifx_abstract
  mdm_log_level: Info
  statsd_port: 8126

  # Volumes
  hostPathName: &mdmHostVolumeName ifx-path
  ifxmetrics_socket_folder_hostPath: &mdmHostPath /var/etw
  ifxmetrics_socket_folder_path: /var/etw
  ifxmetrics_socket_path: /var/etw/mdm_ifx.socket

  # Connection Type
  otlp_metrics_exporter_type: GENEVA_EXPORTER_OTLP_METRICS_ENDPOINT
  applicationEndpoint: &mdmApplicationEndpoint /var/etw/mdm_ifx.socket
  otlp_metrics_endpoint: "Endpoint=unix:/var/etw/mdm_ifx.socket;Account=datalabs;Namespace=datalabs"

  # Leave metric_endpoint commented out for PROD environment. Uncomment it for INT environment.
  metricEndpoint: https://global.ppe.microsoftmetrics.com/
  
  accountInfo:
    DataLabs:
      account: DataLabs
      namespace: DataLabs

  # kubelet identity objectid
  configData: >
    {
      "imdsInfo": [
        {
          "account": "DataLabs",
          "objectId": "7e6eff62-91a5-4b04-bd11-c9a7fcc5e525" 
        }
      ]
    }
