{{- if and .Values.resourceProxyService.enabled .Values.resourceProxyService.partnerCertificates.isEnabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.resourceProxyService.partnerCertificates.secretProviderClassName }}
  namespace: {{ .Values.solutionNameSpace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.clientId }}
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.resourceProxyService.partnerCertificates.tenantId }}
    objects:  |
      array:
          {{- if .Values.resourceProxyService.partnerCertificates.armClient.certificateName }}
        - |
          objectName: {{ .Values.resourceProxyService.partnerCertificates.armClient.certificateName }}
          objectType: secret
          {{- end }}
          {{- if .Values.resourceProxyService.partnerCertificates.qfdClient.certificateName }}
        - |
          objectName: {{ .Values.resourceProxyService.partnerCertificates.qfdClient.certificateName }}
          objectType: secret
          {{- end }}
          {{- if and .Values.resourceProxyService.partnerCertificates.casClient.certificateName (ne .Values.resourceProxyService.partnerCertificates.casClient.certificateName .Values.resourceProxyService.partnerCertificates.qfdClient.certificateName) }}
        - |
          objectName: {{ .Values.resourceProxyService.partnerCertificates.casClient.certificateName }}
          objectType: secret
          {{- end }}
          {{- if .Values.resourceProxyService.partnerCertificates.armAdminClient.certificateName }}
        - |
          objectName: {{ .Values.resourceProxyService.partnerCertificates.armAdminClient.certificateName }}
          objectType: secret
          {{- end }}
{{- end }}
