kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ultra-disk-sc
provisioner: disk.csi.azure.com # replace with "kubernetes.io/azure-disk" if aks version is less than 1.21
volumeBindingMode: WaitForFirstConsumer # optional, but recommended if you want to wait until the pod that will use this disk is created 
parameters:
  skuname: UltraSSD_LRS
  kind: managed
  cachingMode: None
  diskIOPSReadWrite: "8000"  # minimum value: 2 IOPS/GiB, From Pacific Config, Adjust IOPS as needed
  diskMBpsReadWrite: "1600"   # minimum value: 0.032/GiB, From Pacific Config, Adjust throughput as needed        