kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: premium-zrs
provisioner: disk.csi.azure.com # replace with "kubernetes.io/azure-disk" if aks version is less than 1.21
volumeBindingMode: WaitForFirstConsumer # optional, but recommended if you want to wait until the pod that will use this disk is created
parameters:
  skuname: Premium_ZRS
  kind: managed
  cachingMode: None
  #diskIopsReadWrite: "2000"  # minimum value: 2 IOPS/GiB 
  #diskMbpsReadWrite: "320"   # minimum value: 0.032/GiB