# Values File for ABC in INT Environment
agentPoolName: agentpool2
primaryRegionName: "p-eus"
backupRegionName: "b-eus"

solutionInfo:
  solutionName: &solutionName abcsolution
  aksClusterName: abcinteusaks
  environment: INT
  region: eastus
  scaleUnit: *solutionName

# use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
ioServiceAccount:
  # Replace Client Id with MI's Client Id
  clientId: 7a3dbcb9-916a-47e8-b2ee-f9118105df26
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47

ioConfigMap:
  inputEventHubNameSpaceAndName: "abcinteusipehns0/0abcinteusipeh;abcinteusipehns0/abcinteusipeh;abcinteuspremipehns0/abcinteuspremipeh" 
  backupInputEventHubNameSpaceAndName : "abcinteusbipehns0/abcinteusbipeh/00:05:00"
  startBackupInputProvidersAtStartup : true
  outputEventHubNameSpaceAndName: "abcinteusopehns0/abcinteusopeh"
  eventHubStorageAccountName: "0abcinteusehcpsa"
  blobStorageAccountNames: "0abcinteussotsa;1abcinteussotsa"
  backupBlobStorageAccountNames: "0abcinteussotsa;1abcinteussotsa"
  serviceBusNameSpaceAndName: "abcinteussb0/0abcinteussbq"
  outputDataset: "RecoveryServices"
  globalConcurrency: "2000"
  inputChannelConcurrency: "30"
  allowedOutputTypes: "microsoft.azurebusinesscontinuity/unifiedprotecteditems;microsoft.azurebusinesscontinuity/deletedunifiedprotecteditems"
  trafficTuner:
    "allowalltenants: false;
    stopalltenants: false;
    includedregions:;
    includedsubscriptions:
      72f988bf-86f1-41af-91ab-2d7cd011db47 = 6c48fa17-39c7-45f1-90ac-47a587128ace, 38304e13-357e-405e-9e9a-220351dcce8c, 509099b2-9d2c-4636-b43e-bd5cafb6be69, 605e5f88-99d5-4be1-965d-445852415039;
    excludedsubscriptions:;
    excludedresourcetypes:;
    messageretrycutoffcount: 12"
  partnerTrafficTuner:
    "allowalltenants: false;
    stopalltenants: false;
    includedregions:;
    includedsubscriptions:
      72f988bf-86f1-41af-91ab-2d7cd011db47 = 6c48fa17-39c7-45f1-90ac-47a587128ace, 38304e13-357e-405e-9e9a-220351dcce8c, 509099b2-9d2c-4636-b43e-bd5cafb6be69, 605e5f88-99d5-4be1-965d-445852415039;
    excludedsubscriptions:;
    excludedresourcetypes:;
    messageretrycutoffcount: 12"
  backupProviderInputTrafficTunerRule:
    "allowalltenants: false;
    stopalltenants: false;
    includedregions:;
    includedsubscriptions:
      72f988bf-86f1-41af-91ab-2d7cd011db47 = 6c48fa17-39c7-45f1-90ac-47a587128ace, 38304e13-357e-405e-9e9a-220351dcce8c, 509099b2-9d2c-4636-b43e-bd5cafb6be69, 605e5f88-99d5-4be1-965d-445852415039;
    excludedsubscriptions:;
    excludedresourcetypes:;
    messageretrycutoffcount: 12"
  backupProviderPartnerTrafficTunerRule:
    "allowalltenants: false;
    stopalltenants: true;
    includedregions:;
    includedsubscriptions:
      72f988bf-86f1-41af-91ab-2d7cd011db47 = 6c48fa17-39c7-45f1-90ac-47a587128ace, 38304e13-357e-405e-9e9a-220351dcce8c, 509099b2-9d2c-4636-b43e-bd5cafb6be69, 605e5f88-99d5-4be1-965d-445852415039;
    excludedsubscriptions:;
    excludedresourcetypes:;
    messageretrycutoffcount: 12"
  arnPublishStorageAccountNames: "0abcinteusarnpsa;1abcinteusarnpsa"
  arnPublishEventGridDomainIds: "/subscriptions/02d59989-f8a9-4b69-9919-1ef51df4eff6/resourceGroups/DataLabsabcRG-eastus/providers/Microsoft.EventGrid/domains/abcinteusapeg1"
  arnPublishEventGridDomainEndpoints: "https://abcinteusapeg1.eastus-1.eventgrid.azure.net/api/events"
  arnPublishEventGridTopics: "/subscriptions/02d59989-f8a9-4b69-9919-1ef51df4eff6/resourceGroups/DataLabsabcRG-eastus/providers/Microsoft.EventGrid/domains/abcinteusapeg1/topics/arnpublishtopic"
  pairedRegionArnPublishEventGridDomainIds: "/subscriptions/02d59989-f8a9-4b69-9919-1ef51df4eff6/resourceGroups/DataLabsabcRG-eastus/providers/Microsoft.EventGrid/domains/abcinteusapeg1"
  pairedRegionArnPublishEventGridDomainEndpoints: "https://abcinteusapeg1.eastus-1.eventgrid.azure.net/api/events"
  pairedRegionArnPublishEventGridTopics: "/subscriptions/02d59989-f8a9-4b69-9919-1ef51df4eff6/resourceGroups/DataLabsabcRG-eastus/providers/Microsoft.EventGrid/domains/abcinteusapeg1/topics/arnpublishtopic"
  inputCacheTypes: microsoft.recoveryservices/vaults/replicationpolicies;microsoft.compute/virtualmachines;microsoft.storage/storageaccounts;microsoft.resources/subscriptions/resourcegroups;microsoft.resources/subscriptions;microsoft.compute/disks;microsoft.containerservice/managedclusters;microsoft.storage/storageaccounts/blobservices;microsoft.dbforpostgresql/servers;microsoft.dbforpostgresql/flexibleservers;microsoft.recoveryservices/vaults;microsoft.dataprotection/backupvaults;microsoft.classiccompute/virtualmachines
  defaultInputCacheTTL: "2.00:00:00"
  defaultOutputCacheTTL: "01:00:00"
  defaultNotFoundEntryCacheTTL: "01:00:00"
  resourceTypeCacheTTLMappings:
    "microsoft.recoveryservices/vaults/replicationpolicies|2.00:00:00;
    microsoft.compute/virtualmachines|2.00:00:00;
    microsoft.storage/storageaccounts|2.00:00:00;
    microsoft.resources/subscriptions/resourcegroups|2.00:00:00;
    microsoft.resources/subscriptions|2.00:00:00;
    microsoft.compute/disks|2.00:00:00;
    microsoft.containerservice/managedclusters|2.00:00:00;
    microsoft.storage/storageaccounts/blobservices|2.00:00:00;
    microsoft.dbforpostgresql/servers|2.00:00:00;
    microsoft.dbforpostgresql/flexibleservers|2.00:00:00;
    microsoft.recoveryservices/vaults|2.00:00:00;
    microsoft.dataprotection/backupvaults|2.00:00:00;
    microsoft.classiccompute/virtualmachines|2.00:00:00"
  enableBlobPayloadRouting: "false"
  blobPayloadRoutingTypes:
    "microsoft.recoveryservices/vaults/replicationfabrics/replicationprotectioncontainers/replicationprotecteditems;
    microsoft.recoveryservices/vaults/backupfabrics/protectioncontainers/protecteditems;
    microsoft.dataprotection/backupvaults/backupinstances;
    microsoft.DataProtection/backupVaults/deletedBackupInstances"

cacheService:
  enabled: true
  requestMemory: 2Gi
  requestStorage: 4Gi
  requestCPU: 100m
  storageClassName: managed-csi
  volumeClaimName: data
  maxMainStoreMemory: 2g
  maxHashIndexMemory: 1g
  maxCompactionSegments: 2
  cacheConfigMap:
    checkPointIntervalDuration: "00:15:00"
  cachePools:
  - cacheName: iocache1
    readEnabled: true
    writeEnabled: true
    nodePoolName: cachepool1
    nodeCount: 1
    port: 3278
    nodeReplication:
    startOffset: 0
  - cacheName: iocache2
    readEnabled: true
    writeEnabled: true
    nodePoolName: cachepool2
    nodeCount: 1
    port: 3279
    nodeReplication:
    startOffset: 0
  - cacheName: iocache3
    readEnabled: true
    writeEnabled: true
    nodePoolName: cachepool3
    nodeCount: 1
    port: 3280
    nodeReplication:
    startOffset: 0

partnerConfig:    
  pods:
  - name: bcdr-solution
    serviceName: bcdr-solution-service 
    replicaCount: 3
    partnerConfigMap:
      name: bcdr-solution-config   
    containers:
     - name: abcpartnersolution
       repository: datalabsintacr.azurecr.io/abcpartnersolution
       tag: [[<BUILD_VERSION>]]
       port: 5072
       multiResponseResourcesMatchTypes: | 
                      {
                      "resourceTypes" :  "*" 
                      }

resourceProxyService:
  resourceFetcherEndpoints: http://rfinteusaks.abc.int.eusaks:6072
  resourceFetcherTokenResource: https://resourcefetcherservice-int.microsoft.com
  resourceFetcherHomeTenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47

resourceProxyConfigMap:
  getResourceAllowedTypes:
    "microsoft.azurebusinesscontinuity/unifiedprotecteditems:outputsourceoftruth;
     microsoft.azurebusinesscontinuity/deletedunifiedprotecteditems:outputsourceoftruth;
     microsoft.azurebusinesscontinuity/idtodeletedupimappings:outputsourceoftruth;
     microsoft.azurebusinesscontinuity/idtoupimappings:outputsourceoftruth;
     microsoft.recoveryservices/vaults/replicationpolicies:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.compute/virtualmachines:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.storage/storageaccounts:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.resources/subscriptions/resourcegroups:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.resources/subscriptions:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.compute/disks:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.containerservice/managedclusters:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.storage/storageaccounts/blobservices:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.dbforpostgresql/servers:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.dbforpostgresql/flexibleservers:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.recoveryservices/vaults:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.dataprotection/backupvaults:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.classiccompute/virtualmachines:cache|write|addNotFound,resourcefetcher_arm"

resourceProxyServiceAccount:
  clientId: 7a3dbcb9-916a-47e8-b2ee-f9118105df26
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47

# Monitoring configurations
monitorInfo:
  exporterType: GENEVA # default is console exporter
  isInternalPartner: false

genevaAccounts:
  partner:
    gcs_environment: Test
    gcs_account: abctestlsacc
    gcs_region: eastus
    gcs_namespace: abctestlsacc
    gcs_config_version: "1.1" 
    miResourceId: /subscriptions/02d59989-f8a9-4b69-9919-1ef51df4eff6/resourcegroups/MC_DataLabsabcRG-eastus_abcinteusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/abcinteusaks-agentpool

  datalabs:
    gcs_environment: Test
    gcs_account: DataLabs
    gcs_region: eastus
    gcs_namespace: DataLabs
    gcs_config_version: "1.6" 
    miResourceId: /subscriptions/02d59989-f8a9-4b69-9919-1ef51df4eff6/resourcegroups/MC_DataLabsabcRG-eastus_abcinteusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/abcinteusaks-agentpool

mdm:
  # Leave metric_endpoint commented out for PROD environment. Uncomment it for INT environment.
  metricEndpoint: https://global.ppe.microsoftmetrics.com/
  
  accountInfo:
    DataLabs:
      account: DataLabs
      namespace: DataLabs
    Partner: # Change accountInfo for Partner (can be the same as DataLabs)
      account: abctestlsacc
      namespace: abctestlsacc
    Customer:
      account: abctestcustomeracc
      namespace: abctestcustomeracc

  configData: >
    {
      "imdsInfo": [
        {
          "account": "abctestlsacc",
          "objectId": "40a07c74-6ae9-45f8-8e58-2308d0f84325"
        },
        {
          "account": "abctestcustomeracc",
          "objectId": "40a07c74-6ae9-45f8-8e58-2308d0f84325"
        },
        {
          "account": "DataLabs",
          "objectId": "40a07c74-6ae9-45f8-8e58-2308d0f84325"
        }
      ]
    }

keyVault:
  name: abcinteuskv
  clientId: 271b3d5a-31f2-4957-a2d5-1da51e8e2d57

adminService:
  isEnabled: false
  sslSecretProvider:
    certificateName: abcinteusaks-ssl

adminServiceConfigMap:
  dstsRealm: realm://dsts.core.azure-test.net/
  dstsName: co2agg04-dsts.dsts.core.azure-test.net
  serviceDns: int.datalabs.core.windows.net
  allowedActors: GenevaActionsTest,acisTestTodSMSTest,GenevaActionsDelegatedAuthNonProd