# Values File for ABC in Canary Environment
primaryRegionName: "p-ecy"
backupRegionName: "b-ecy"

solutionInfo:
  solutionName: &solutionName abcsolution
  aksClusterName: abccanaryecyaks
  environment: Canary
  region: eastus2euap
  scaleUnit: *solutionName

# use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
ioServiceAccount: 
# MI of abc partner
  clientId: 04c3d0a2-2cb5-4e0c-b1ab-66fd0ce9ae9e 
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

ioConfigMap:
  inputEventHubNameSpaceAndName: "abccanaryecyipehns0/abccanaryecyipeh;abccanaryecyipehns1/abccanaryecyipeh;abccanaryecyipehns2/abccanaryecyipeh;abccanaryecyipehns3/abccanaryecyipeh;abccanaryecyipehns4/abccanaryecyipeh;abccanaryecyipehns5/abccanaryecyipeh" # flighting event hub
  outputEventHubNameSpaceAndName: "abccanaryecyopehns0/abccanaryecyopeh"
  eventHubStorageAccountName: "0abccanaryecyehcpsa"
  blobStorageAccountNames: "0abccanaryecysotsa;1abccanaryecysotsa"
  backupInputEventHubNameSpaceAndName: "abccanaryecybipehns0/abccanaryecybipeh/00:05:00;abccanaryecybipehns1/abccanaryecybipeh/00:05:00;abccanaryecybipehns2/abccanaryecybipeh/00:05:00;abccanaryecybipehns3/abccanaryecybipeh/00:05:00;abccanaryecybipehns4/abccanaryecybipeh/00:05:00;abccanaryecybipehns5/abccanaryecybipeh/00:05:00"
  backupBlobStorageAccountNames: "0abccanaryecysotsa;1abccanaryecysotsa"
  serviceBusNameSpaceAndName: "abccanaryecysb0/0abccanaryecysbq"
  outputDataset: "RecoveryServices"
  globalConcurrency: "4000"
  inputChannelConcurrency: "600"
  rawInputChannelConcurrency: "200"
  allowedOutputTypes: "microsoft.azurebusinesscontinuity/unifiedprotecteditems;microsoft.azurebusinesscontinuity/deletedunifiedprotecteditems"
  trafficTuner:
    "allowalltenants: false;
    stopalltenants: false;
    includedregions:;
    includedsubscriptions:
      9329c02a-4050-4798-93ae-b6e37b19af6d = ca8db99c-7ec7-472f-a992-9934e8ad1b6a, 43957aaa-9863-4d9e-bf14-eb296d70676c|
      72f988bf-86f1-41af-91ab-2d7cd011db47 = 1a2311d9-66f5-47d3-a9fb-7a37da63934b, 62b829ee-7936-40c9-a1c9-47a93f9f3965, 7c943c1b-5122-4097-90c8-861411bdd574, b364ed8d-4279-4bf8-8fd1-56f8fa0ae05c, b8aef8e1-37df-4f17-a537-f10e183c8eca;
    excludedsubscriptions:;
    excludedresourcetypes:;
    messageretrycutoffcount: 12"
  partnerTrafficTuner:
    "allowalltenants: false;
    stopalltenants: false;
    includedregions:;
    includedsubscriptions:
      9329c02a-4050-4798-93ae-b6e37b19af6d = ca8db99c-7ec7-472f-a992-9934e8ad1b6a, 43957aaa-9863-4d9e-bf14-eb296d70676c|
      72f988bf-86f1-41af-91ab-2d7cd011db47 = 1a2311d9-66f5-47d3-a9fb-7a37da63934b, 62b829ee-7936-40c9-a1c9-47a93f9f3965, 7c943c1b-5122-4097-90c8-861411bdd574, b364ed8d-4279-4bf8-8fd1-56f8fa0ae05c, b8aef8e1-37df-4f17-a537-f10e183c8eca;
    excludedsubscriptions:;
    excludedresourcetypes:;
    messageretrycutoffcount: 12"
  backupProviderInputTrafficTunerRule:
    "allowalltenants: false;
    stopalltenants: false;
    includedregions:;
    includedsubscriptions:
      9329c02a-4050-4798-93ae-b6e37b19af6d = ca8db99c-7ec7-472f-a992-9934e8ad1b6a, 43957aaa-9863-4d9e-bf14-eb296d70676c|
      72f988bf-86f1-41af-91ab-2d7cd011db47 = 1a2311d9-66f5-47d3-a9fb-7a37da63934b, 62b829ee-7936-40c9-a1c9-47a93f9f3965, 7c943c1b-5122-4097-90c8-861411bdd574, b364ed8d-4279-4bf8-8fd1-56f8fa0ae05c, b8aef8e1-37df-4f17-a537-f10e183c8eca;
    excludedsubscriptions:;
    excludedresourcetypes:;
    messageretrycutoffcount: 12"
  backupProviderPartnerTrafficTunerRule:
    "allowalltenants: false;
    stopalltenants: true;
    includedregions:;
    includedsubscriptions:
      9329c02a-4050-4798-93ae-b6e37b19af6d = ca8db99c-7ec7-472f-a992-9934e8ad1b6a, 43957aaa-9863-4d9e-bf14-eb296d70676c|
      72f988bf-86f1-41af-91ab-2d7cd011db47 = 1a2311d9-66f5-47d3-a9fb-7a37da63934b, 62b829ee-7936-40c9-a1c9-47a93f9f3965, 7c943c1b-5122-4097-90c8-861411bdd574, b364ed8d-4279-4bf8-8fd1-56f8fa0ae05c, b8aef8e1-37df-4f17-a537-f10e183c8eca;
    excludedsubscriptions:;
    excludedresourcetypes:;
    messageretrycutoffcount: 12"
  arnPublishStorageAccountNames: "0abccanaryecyarnpsa;1abccanaryecyarnpsa;2abccanaryecyarnpsa;3abccanaryecyarnpsa;4abccanaryecyarnpsa;5abccanaryecyarnpsa"
  arnPublishEventGridDomainIds: "/subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/DataLabsabcRG-eastus2euap/providers/Microsoft.EventGrid/domains/abccanaryecyapeg1;/subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/DataLabsabcRG-eastus2euap/providers/Microsoft.EventGrid/domains/abccanaryecyapeg2"
  arnPublishEventGridDomainEndpoints: "https://abccanaryecyapeg1.eastus2euap-1.eventgrid.azure.net/api/events;https://abccanaryecyapeg2.eastus2euap-1.eventgrid.azure.net/api/events"
  arnPublishEventGridTopics: "/subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/DataLabsabcRG-eastus2euap/providers/Microsoft.EventGrid/domains/abccanaryecyapeg1/topics/arnpublishtopic;/subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/DataLabsabcRG-eastus2euap/providers/Microsoft.EventGrid/domains/abccanaryecyapeg2/topics/arnpublishtopic"
  pairedRegionArnPublishEventGridDomainIds: "/subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/DataLabsabcRG-eastus2euap/providers/Microsoft.EventGrid/domains/abccanaryecyapeg1;/subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/DataLabsabcRG-eastus2euap/providers/Microsoft.EventGrid/domains/abccanaryecyapeg2"
  pairedRegionArnPublishEventGridDomainEndpoints: "https://abccanaryecyapeg1.eastus2euap-1.eventgrid.azure.net/api/events;https://abccanaryecyapeg2.eastus2euap-1.eventgrid.azure.net/api/events"
  pairedRegionArnPublishEventGridTopics: "/subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/DataLabsabcRG-eastus2euap/providers/Microsoft.EventGrid/domains/abccanaryecyapeg1/topics/arnpublishtopic;/subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/DataLabsabcRG-eastus2euap/providers/Microsoft.EventGrid/domains/abccanaryecyapeg2/topics/arnpublishtopic"
  inputCacheTypes: microsoft.recoveryservices/vaults/replicationpolicies;microsoft.compute/virtualmachines;microsoft.storage/storageaccounts;microsoft.resources/subscriptions/resourcegroups;microsoft.resources/subscriptions;microsoft.compute/disks;microsoft.containerservice/managedclusters;microsoft.storage/storageaccounts/blobservices;microsoft.dbforpostgresql/servers;microsoft.dbforpostgresql/flexibleservers;microsoft.recoveryservices/vaults;microsoft.dataprotection/backupvaults;microsoft.classiccompute/virtualmachines
  defaultInputCacheTTL: "2.00:00:00"
  defaultOutputCacheTTL: "01:00:00"
  defaultNotFoundEntryCacheTTL: "01:00:00"
  resourceTypeCacheTTLMappings:
    "microsoft.recoveryservices/vaults/replicationpolicies|2.00:00:00;
    microsoft.compute/virtualmachines|2.00:00:00;
    microsoft.storage/storageaccounts|2.00:00:00;
    microsoft.resources/subscriptions/resourcegroups|2.00:00:00;
    microsoft.resources/subscriptions|2.00:00:00;
    microsoft.compute/disks|2.00:00:00;
    microsoft.containerservice/managedclusters|2.00:00:00;
    microsoft.storage/storageaccounts/blobservices|2.00:00:00;
    microsoft.dbforpostgresql/servers|2.00:00:00;
    microsoft.dbforpostgresql/flexibleservers|2.00:00:00;
    microsoft.recoveryservices/vaults|2.00:00:00;
    microsoft.dataprotection/backupvaults|2.00:00:00;
    microsoft.classiccompute/virtualmachines|2.00:00:00"
  enableBlobPayloadRouting: "false"
  blobPayloadRoutingTypes:
    "microsoft.recoveryservices/vaults/replicationfabrics/replicationprotectioncontainers/replicationprotecteditems;
    microsoft.recoveryservices/vaults/backupfabrics/protectioncontainers/protecteditems;
    microsoft.dataprotection/backupvaults/backupinstances;
    microsoft.DataProtection/backupVaults/deletedBackupInstances"

cacheService:
  enabled: true
  requestMemory: 40Gi
  requestStorage: 1024Gi
  maxMainStoreMemory: 32g
  maxHashIndexMemory: 4g
  maxCompactionSegments: 500
  cachePools:
  - cacheName: iocache
    readEnabled: true
    writeEnabled: true
    nodePoolName: cachepool
    nodeCount: 3
    port: 3278
    nodeReplication:
    startOffset: 0

partnerConfig:    
  pods:
  - name: bcdr-solution
    serviceName: bcdr-solution-service 
    partnerConfigMap:
      name: bcdr-solution-config  
    containers:
     - name: abcpartnersolution
       repository: datalabscanaryacr.azurecr.io/abcpartnersolution
       tag: [[<BUILD_VERSION>]]
       port: 5072
       concurrency: 0
       multiResponseResourcesMatchTypes: | 
                      {
                      "resourceTypes" :  "*" 
                      }

resourceProxyService:
  resourceFetcherEndpoints: http://rfcanaryecyaks.abc.canary.ecyaks:6072
  resourceFetcherTokenResource: https://resourcefetcherservice-canary.msazurecloud.onmicrosoft.com

resourceProxyConfigMap:
  getResourceAllowedTypes:
    "microsoft.azurebusinesscontinuity/unifiedprotecteditems:outputsourceoftruth;
     microsoft.azurebusinesscontinuity/deletedunifiedprotecteditems:outputsourceoftruth;
     microsoft.azurebusinesscontinuity/idtodeletedupimappings:outputsourceoftruth;
     microsoft.azurebusinesscontinuity/idtoupimappings:outputsourceoftruth;
     microsoft.recoveryservices/vaults/replicationpolicies:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.compute/virtualmachines:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.storage/storageaccounts:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.resources/subscriptions/resourcegroups:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.resources/subscriptions:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.compute/disks:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.containerservice/managedclusters:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.storage/storageaccounts/blobservices:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.dbforpostgresql/servers:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.dbforpostgresql/flexibleservers:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.recoveryservices/vaults:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.dataprotection/backupvaults:cache|write|addNotFound,resourcefetcher_arm;
     microsoft.classiccompute/virtualmachines:cache|write|addNotFound,resourcefetcher_arm"

resourceProxyServiceAccount: 
# MI of idm partner
  clientId: 04c3d0a2-2cb5-4e0c-b1ab-66fd0ce9ae9e 

# Monitoring information
monitorInfo:
  exporterType: GENEVA # default is console exporter
  isInternalPartner: false

genevaAccounts:
  partner: # Comment out section if partner will use Data Labs geneva account
    gcs_environment: DiagnosticsProd
    gcs_account: AzureBusinessContinuity
    gcs_region: eastus2euap
    gcs_namespace: AzureBusinessContinuity
    gcs_config_version: "1.5"
    miResourceId: /subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/MC_DataLabsABCRG-eastus2euap_abccanaryecyaks_eastus2euap/providers/Microsoft.ManagedIdentity/userAssignedIdentities/abccanaryecyaks-agentpool
  
  datalabs:
    gcs_environment: DiagnosticsProd
    gcs_account: ARGDataLabs
    gcs_region: eastus2euap
    gcs_namespace: ARGDataLabs
    gcs_config_version: "1.5" 
    miResourceId: /subscriptions/75e7e676-7873-4432-98bd-01a68cc5bca1/resourceGroups/MC_DataLabsABCRG-eastus2euap_abccanaryecyaks_eastus2euap/providers/Microsoft.ManagedIdentity/userAssignedIdentities/abccanaryecyaks-agentpool

mdm:
  # Leave metric_endpoint commented out for PROD environment. Uncomment it for INT environment.
  # metricEndpoint: https://global.ppe.microsoftmetrics.com/

  accountInfo:
    DataLabs:
      account: ARGDataLabs
      namespace: ARGDataLabs
    Partner: # Change accountInfo for Partner (can be the same as DataLabs)
      account: AzureBusinessContinuity
      namespace: AzureBusinessContinuity
    Customer:
      account: CustomerAzureBusinessContinuity
      namespace: CustomerAzureBusinessContinuity

  # objectId of abc aks-agentpool MI (kubelet identity)
  configData: >
    {
      "imdsInfo": [
        {
          "account": "ARGDataLabs",
          "objectId": "66fade2d-0bc3-425a-b48f-ecf2408a0341" 
        },
        {
          "account": "AzureBusinessContinuity",
          "objectId": "66fade2d-0bc3-425a-b48f-ecf2408a0341"
        },
        {
          "account": "CustomerAzureBusinessContinuity",
          "objectId": "66fade2d-0bc3-425a-b48f-ecf2408a0341"
        }
      ]
    }
