# Values File for pol in INT Environment
agentPoolName: agentpool
primaryRegionName: "p-ecy"
backupRegionName: "b-ecy"

solutionInfo:
  solutionName: &solutionName capsolution
  aksClusterName: capcanaryecyaks
  environment: Canary
  region: eastus2euap
  scaleUnit: *solutionName

# use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
# az identity show --resource-group "DataLabscapRG" --name "capcanaryioconnectorid" --query 'clientId' -otsv
ioServiceAccount:
  # Replace Client Id with MI's Client Id
  clientId: 022206f3-5dbc-458f-89a1-f876aa30d01f  # todo: replace with MI of cap partner
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

ioConfigMap:
  inputEventHubNameSpaceAndName: 'capcanaryecyipehns0/capcanaryecyipeh;capcanaryecyipehns1/capcanaryecyipeh' # flighting event hub
  backupInputEventHubNameSpaceAndName : "capcanaryecybipehns0/capcanaryecybipeh/00:05:00"
  outputEventHubNameSpaceAndName: "capcanaryecyopehns0/capcanaryecyopeh"
  eventHubStorageAccountName: "0capcanaryecyehcpsa"
  blobStorageAccountNames: "0capcanaryecysotsa;1capcanaryecysotsa"
  backupBlobStorageAccountNames: "0capcanaryecysotsa;1capcanaryecysotsa"
  useSourceOfTruth: "true"
  serviceBusNameSpaceAndName: "capcanaryecysb0/0capcanaryecysbq"
  outputDataset: "resourcecapabilities"
  allowedOutputTypes: "microsoft.resources/capabilities"
  publishOutputToArn: "false"
  arnPublishStorageAccountNames: "0capcanaryecyarnpsa;1capcanaryecyarnpsa"
  arnPublishEventGridDomainIds: "/subscriptions/67593859-7d8e-4115-858d-e371e0461a57/resourceGroups/DataLabscapRG-eastus2euap/providers/Microsoft.EventGrid/domains/capcanaryecyapeg1"
  arnPublishEventGridDomainEndpoints: "https://capcanaryecyapeg1.eastus2euap-1.eventgrid.azure.net/api/events"
  arnPublishEventGridTopics: "/subscriptions/67593859-7d8e-4115-858d-e371e0461a57/resourceGroups/DataLabscapRG-eastus2euap/providers/Microsoft.EventGrid/domains/capcanaryecyapeg1/topics/arnpublishtopic"

partnerConfig:    
  pods:
  - name: pol-cap-solution
    serviceName: pol-cap-solution-service 
    replicaCount: 3
    partnerConfigMap:
      name: pol-cap-solution-config
    containers:
     - name: cappartnersolution
       repository: datalabscanaryacr.azurecr.io/cappartnersolution
       tag: [[<BUILD_VERSION>]]
       port: 5072
       singleResponseResourcesMatchTypes: | 
                      {
                      "resourceTypes" :  "*" 
                      }

resourceProxyConfigMap:
  resourceFetcherServiceEndpoint: http://rfcanaryecyaks.cap.canary.ecyaks/
  resourceFetcherAADTokenResource: https://resourcefetcherservice-canary.msazurecloud.onmicrosoft.com
  resourceFetcherAADHomeTenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

resourceProxyConfigMap:
  callARMGenericRequestAllowedTypes:
    "/providers/Microsoft.Authorization/policySetDefinitions:resourcefetcher_arm;
    /providers/Microsoft.Authorization/policyDefinitions:resourcefetcher_arm;
    /providers:resourcefetcher_arm"

# Replace Client Id with MI's Client Id
resourceProxyServiceAccount:
  clientId: 022206f3-5dbc-458f-89a1-f876aa30d01f
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

cacheService:
  enabled: false

# Monitoring configurations
monitorInfo:
  exporterType: GENEVA # default is console exporter
  isInternalPartner: false

genevaAccounts:
  datalabs:
    gcs_environment: DiagnosticsProd
    gcs_account: ARGDataLabs
    gcs_region: eastus2euap
    gcs_namespace: ARGDataLabs
    gcs_config_version: '1.6' # parameterized in the future
    miResourceId: /subscriptions/67593859-7d8e-4115-858d-e371e0461a57/resourcegroups/MC_DataLabscapRG-eastus2euap_capcanaryecyaks_eastus2euap/providers/Microsoft.ManagedIdentity/userAssignedIdentities/capcanaryecyaks-agentpool
  partner:
    gcs_environment: DiagnosticsProd
    gcs_account: GovernanceAKSLinux
    gcs_region: eastus2euap
    gcs_namespace: GovernanceAKSLinux
    gcs_config_version: "1.1"
    miResourceId: /subscriptions/67593859-7d8e-4115-858d-e371e0461a57/resourcegroups/MC_DataLabscapRG-eastus2euap_capcanaryecyaks_eastus2euap/providers/Microsoft.ManagedIdentity/userAssignedIdentities/capcanaryecyaks-agentpool

mdm:
  # Leave metric_endpoint commented out for PROD environment. Uncomment it for INT environment.
  # metricEndpoint: https://global.ppe.microsoftmetrics.com/

  accountInfo:
    DataLabs:
      account: ARGDataLabs
      namespace: ARGDataLabs
    Partner: # Change accountInfo for Partner (can be the same as DataLabs)
      account: GovernanceAKSLinux
      namespace: GovernanceAKSLinux

  # objectId of abc aks-agentpool MI (kubelet identity)
  # (Get-AzAksCluster -ResourceGroupName DataLabscapRG-eastus2euap -Name capcanaryecyaks ).IdentityProfile.kubeletidentity.objectid
  configData: >
    {
      "imdsInfo": [
        {
          "account": "GovernanceAKSLinux",
          "objectId": "d1b9cac9-5a7b-4ca7-b224-b862ba5af54c"
        },
        {
          "account": "DataLabs",
          "objectId": "d1b9cac9-5a7b-4ca7-b224-b862ba5af54c"
        }
      ]
    }
