# Values File for Capabilities in prod eus Environment
agentpoolName: agentpool
primaryRegionName: eus
backupRegionName: wu3

solutionInfo:
  solutionName: &solutionName capsolution
  aksClusterName: capprodeusaks
  environment: Prod
  region: eastus
  scaleUnit: *solutionName

ioService:
  replicaCount: 5 # override from dataLabServices.yaml

# use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
ioServiceAccount:
#MI of cap partner
  clientId: 00012c86-9d41-4ed3-9555-5bf6482cd569
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

ioConfigMap:
  inputEventHubNameSpaceAndName: "capprodeuspipehns0/capprodeuspipeh;capprodeuspipehns1/capprodeuspipeh"
  outputEventHubNameSpaceAndName: ""
  eventHubStorageAccountName: "0capprodeusehcpsa"
  blobStorageAccountNames: "0capprodeussotsa;1capprodeussotsa" # No source of truth
  backupInputEventHubNameSpaceAndName: "capprodeusbpipehns0/capprodeusbpipeh/00:05:00;capprodeusbpipehns1/capprodeusbpipeh/00:05:00"
  backupBlobStorageAccountNames: "0capprodwu3sotsa;1capprodwu3sotsa"
  serviceBusNameSpaceAndName: "capprodeussb0/0capprodeussbq;capprodeussb1/0capprodeussbq"
  outputDataset: 'resourcecapabilities'
  useSourceOfTruth: 'true'
  allowedOutputTypes: "microsoft.resources/capabilities"
  arnPublishStorageAccountNames: "0capprodeusarnpsa;1capprodeusarnpsa;2capprodeusarnpsa;3capprodeusarnpsa;4capprodeusarnpsa;5capprodeusarnpsa"
  arnPublishEventGridDomainIds: "/subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourceGroups/DataLabscapRG-eastus/providers/Microsoft.EventGrid/domains/capprodeusapeg1;/subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourceGroups/DataLabscapRG-eastus/providers/Microsoft.EventGrid/domains/capprodeusapeg2"
  arnPublishEventGridDomainEndpoints: "https://capprodeusapeg1.eastus-1.eventgrid.azure.net/api/events;https://capprodeusapeg2.eastus-1.eventgrid.azure.net/api/events"
  arnPublishEventGridTopics: "/subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourceGroups/DataLabscapRG-eastus/providers/Microsoft.EventGrid/domains/capprodeusapeg1/topics/arnpublishtopic;/subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourceGroups/DataLabscapRG-eastus/providers/Microsoft.EventGrid/domains/capprodeusapeg2/topics/arnpublishtopic"

partnerConfig:
  pods:
  - name: pol-cap-solution
    serviceName: pol-cap-solution-service
    replicaCount: 5
    partnerConfigMap:
      name: pol-cap-solution-config    
    containers:
     - name: cappartnersolution
       repository: datalabsprodacr.azurecr.io/cappartnersolution
       tag: [[<BUILD_VERSION>]]
       port: 5072
       singleResponseResourcesMatchTypes: | 
                      {
                      "resourceTypes" : "*"
                      }

resourceProxyConfigMap:
  resourceFetcherServiceEndpoint: http://rfprodeusaks.cap.prod.eusaks/
  resourceFetcherAADTokenResource: https://resourcefetcherservice-prod.msazurecloud.onmicrosoft.com
  resourceFetcherAADHomeTenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

resourceProxyConfigMap:
  callARMGenericRequestAllowedTypes:
    "/providers/Microsoft.Authorization/policySetDefinitions:resourcefetcher_arm;
    /providers/Microsoft.Authorization/policyDefinitions:resourcefetcher_arm;
    /providers:resourcefetcher_arm"

resourceProxyServiceAccount: 
# MI of cap partner
  clientId: 00012c86-9d41-4ed3-9555-5bf6482cd569
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

cacheService:
  enabled: false
  replicaCount: 5 # override from dataLabServices.yaml

# Monitoring Information
monitorInfo:
  exporterType: GENEVA # default is console exporter
  isInternalPartner: false

genevaAccounts:
  datalabs:
    gcs_environment: DiagnosticsProd
    gcs_account: ARGDataLabs
    gcs_region: eastus
    gcs_namespace: ARGDataLabs
    gcs_config_version: "3.1"
    miResourceId: /subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourcegroups/MC_DataLabscapRG-eastus_capprodeusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/capprodeusaks-agentpool
  partner:
    gcs_environment: DiagnosticsProd
    gcs_account: GovernanceAKSLinux
    gcs_region: eastus
    gcs_namespace: GovernanceAKSLinux
    gcs_config_version: "1.1"
    miResourceId: /subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourcegroups/MC_DataLabscapRG-eastus_capprodeusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/capprodeusaks-agentpool

mdm:
  # Leave metric_endpoint commented out for PROD environment. Uncomment it for INT environment.
  # metricEndpoint: https://global.ppe.microsoftmetrics.com/

  accountInfo:
    DataLabs:
      account: ARGDataLabs
      namespace: ARGDataLabs
    Partner: 
      account: GovernanceAKSLinux
      namespace: GovernanceAKSLinux

  # objectId of cap aks-agentpool MI (kubelet identity)
  configData: >
    {
      "imdsInfo": [
        {
          "account": "ARGDataLabs",
          "objectId": "dc65af9b-51f4-4381-a0df-9a607987314d"
        },
        {
          "account": "GovernanceAKSLinux",
          "objectId": "dc65af9b-51f4-4381-a0df-9a607987314d"
        }
      ]
    }
