# Values File for Capabilities in prod neu Environment
agentpoolName: agentpool
primaryRegionName: neu
backupRegionName: sdc

solutionInfo:
  solutionName: &solutionName capsolution
  aksClusterName: capprodneuaks
  environment: Prod
  region: northeurope
  scaleUnit: *solutionName

ioService:
  replicaCount: 5 # override from dataLabServices.yaml

# use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
ioServiceAccount:
#MI of cap partner
  clientId: 00012c86-9d41-4ed3-9555-5bf6482cd569
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

ioConfigMap:
  inputEventHubNameSpaceAndName: "capprodneupipehns0/capprodneupipeh;capprodneupipehns1/capprodneupipeh"
  outputEventHubNameSpaceAndName: "capprodneuopehns0/capprodneuopeh;capprodneuopehns1/capprodneuopeh"
  publishOutputToArn: "false"
  eventHubStorageAccountName: "0capprodneuehcpsa"
  blobStorageAccountNames: "0capprodneusotsa;1capprodneusotsa" # No source of truth
  backupInputEventHubNameSpaceAndName: "capprodneubpipehns0/capprodneubpipeh/00:05:00;capprodneubpipehns1/capprodneubpipeh/00:05:00"
  backupBlobStorageAccountNames: "0capprodsdcsotsa;1capprodsdcsotsa"
  serviceBusNameSpaceAndName: "capprodneusb0/0capprodneusbq;capprodneusb1/0capprodneusbq"
  outputDataset: 'resourcecapabilities'
  useSourceOfTruth: 'true'
  allowedOutputTypes: "microsoft.resources/capabilities"
  arnPublishStorageAccountNames: "0capprodneuarnpsa;1capprodneuarnpsa;2capprodneuarnpsa;3capprodneuarnpsa;4capprodneuarnpsa;5capprodneuarnpsa"
  arnPublishEventGridDomainIds: "/subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourceGroups/DataLabscapRG-northeurope/providers/Microsoft.EventGrid/domains/capprodneuapeg1;/subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourceGroups/DataLabscapRG-northeurope/providers/Microsoft.EventGrid/domains/capprodneuapeg2"
  arnPublishEventGridDomainEndpoints: "https://capprodneuapeg1.northeurope-1.eventgrid.azure.net/api/events;https://capprodneuapeg2.northeurope-1.eventgrid.azure.net/api/events"
  arnPublishEventGridTopics: "/subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourceGroups/DataLabscapRG-northeurope/providers/Microsoft.EventGrid/domains/capprodneuapeg1/topics/arnpublishtopic;/subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourceGroups/DataLabscapRG-northeurope/providers/Microsoft.EventGrid/domains/capprodneuapeg2/topics/arnpublishtopic"

partnerConfig:    
  pods:
  - name: pol-cap-solution
    serviceName: pol-cap-solution-service
    replicaCount: 5
    partnerConfigMap:
      name: pol-cap-solution-config    
    containers:
     - name: cappartnersolution
       repository: datalabsprodacr.azurecr.io/cappartnersolution
       tag: [[<BUILD_VERSION>]]
       port: 5072
       singleResponseResourcesMatchTypes: | 
                      {
                      "resourceTypes" : "*"
                      }

resourceProxyConfigMap:
  resourceFetcherServiceEndpoint: http://rfprodneuaks.cap.prod.neuaks/
  resourceFetcherAADTokenResource: https://resourcefetcherservice-prod.msazurecloud.onmicrosoft.com
  resourceFetcherAADHomeTenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

resourceProxyConfigMap:
  callARMGenericRequestAllowedTypes:
    "/providers/Microsoft.Authorization/policySetDefinitions:resourcefetcher_arm;
    /providers/Microsoft.Authorization/policyDefinitions:resourcefetcher_arm;
    /providers:resourcefetcher_arm"

resourceProxyServiceAccount: 
# MI of cap partner
  clientId: 00012c86-9d41-4ed3-9555-5bf6482cd569
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

cacheService:
  enabled: false
  replicaCount: 5 # override from dataLabServices.yaml

# Monitoring Information
monitorInfo:
  exporterType: GENEVA # default is console exporter
  isInternalPartner: false

genevaAccounts:
  datalabs:
    gcs_environment: DiagnosticsProd
    gcs_account: ARGDataLabs
    gcs_region: northeurope
    gcs_namespace: ARGDataLabs
    gcs_config_version: "3.1"
    miResourceId: /subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourcegroups/MC_DataLabscapRG-northeurope_capprodneuaks_northeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/capprodneuaks-agentpool
  partner:
    gcs_environment: DiagnosticsProd
    gcs_account: GovernanceAKSLinux
    gcs_region: northeurope
    gcs_namespace: GovernanceAKSLinux
    gcs_config_version: "1.1"
    miResourceId: /subscriptions/75c6bdbd-d177-465c-bd3c-b340c1333167/resourcegroups/MC_DataLabscapRG-northeurope_capprodneuaks_northeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/capprodneuaks-agentpool

mdm:
  # Leave metric_endpoint commented out for PROD environment. Uncomment it for INT environment.
  # metricEndpoint: https://global.ppe.microsoftmetrics.com/

  accountInfo:
    DataLabs:
      account: ARGDataLabs
      namespace: ARGDataLabs
    Partner: 
      account: GovernanceAKSLinux
      namespace: GovernanceAKSLinux

  # objectId of cap aks-agentpool MI (kubelet identity)
  configData: >
    {
      "imdsInfo": [
        {
          "account": "ARGDataLabs",
          "objectId": "e3623686-d2f4-4e6b-a7b2-13bfc597be74"
        },
        {
          "account": "GovernanceAKSLinux",
          "objectId": "e3623686-d2f4-4e6b-a7b2-13bfc597be74"
        }
      ]
    }
