# Values File for IDMapping in prod eus Environment
primaryRegionName: eus
backupRegionName: wu3

solutionInfo:
  solutionName: &solutionName idmapping
  aksClusterName: idmprodeusaks
  environment: Prod
  region: eastus
  scaleUnit: *solutionName

ioService:
  replicaCount: 5 # override from dataLabServices.yaml

# use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
ioServiceAccount:
#MI of idm partner
  clientId: 0d27a978-3ca2-4d6b-9fa6-031e2c34bfb0
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

ioConfigMap:
  inputEventHubNameSpaceAndName: "idmprodeuspipehns0/idmprodeuspipeh;idmprodeuspipehns1/idmprodeuspipeh"
  outputEventHubNameSpaceAndName: "idmprodeusopehns0/idmprodeusopeh"
  eventHubStorageAccountName: "0idmprodeusehcpsa"
  blobStorageAccountNames: "" # No source of truth
  backupInputEventHubNameSpaceAndName: "idmprodeusbpipehns0/idmprodeusbpipeh/00:05:00;idmprodeusbpipehns1/idmprodeusbpipeh/00:05:00"
  backupBlobStorageAccountNames: ""
  serviceBusNameSpaceAndName: "idmprodeussb0/0idmprodeussbq;idmprodeussb1/1idmprodeussbq"
  outputDataset: 'idmapping'
  useSourceOfTruth: 'false'
  allowedOutputTypes: "microsoft.idmapping/identifiers"
  arnPublishStorageAccountNames: "0idmprodeusarnpsa;1idmprodeusarnpsa;2idmprodeusarnpsa;3idmprodeusarnpsa;4idmprodeusarnpsa;5idmprodeusarnpsa"
  arnPublishEventGridDomainIds: "/subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourceGroups/DataLabsidmRG-eastus/providers/Microsoft.EventGrid/domains/idmprodeusapeg1;/subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourceGroups/DataLabsidmRG-eastus/providers/Microsoft.EventGrid/domains/idmprodeusapeg2"
  arnPublishEventGridDomainEndpoints: "https://idmprodeusapeg1.eastus-1.eventgrid.azure.net/api/events;https://idmprodeusapeg2.eastus-1.eventgrid.azure.net/api/events"
  arnPublishEventGridTopics: "/subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourceGroups/DataLabsidmRG-eastus/providers/Microsoft.EventGrid/domains/idmprodeusapeg1/topics/arnpublishtopic;/subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourceGroups/DataLabsidmRG-eastus/providers/Microsoft.EventGrid/domains/idmprodeusapeg2/topics/arnpublishtopic"
  pairedRegionArnPublishEventGridDomainIds: "/subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourceGroups/DataLabsidmRG-westus3/providers/Microsoft.EventGrid/domains/idmprodwu3apeg1;/subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourceGroups/DataLabsidmRG-westus3/providers/Microsoft.EventGrid/domains/idmprodwu3apeg2"
  pairedRegionArnPublishEventGridDomainEndpoints: "https://idmprodwu3apeg1.westus3-1.eventgrid.azure.net/api/events;https://idmprodwu3apeg2.westus3-1.eventgrid.azure.net/api/events"
  pairedRegionArnPublishEventGridTopics: "/subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourceGroups/DataLabsidmRG-westus3/providers/Microsoft.EventGrid/domains/idmprodwu3apeg1/topics/arnpublishtopic;/subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourceGroups/DataLabsidmRG-westus3/providers/Microsoft.EventGrid/domains/idmprodwu3apeg2/topics/arnpublishtopic"
  outputChannelBufferDelay: "100"

partnerConfig:    
  pods:
  - name: idmapping-solution
    serviceName: idmapping-solution-service
    replicaCount: 5
    partnerConfigMap:
      name: idmapping-solution-config    
    containers:
     - name: idmpartnersolution
       repository: datalabsprodacr.azurecr.io/idmpartnersolution
       tag: [[<BUILD_VERSION>]]
       port: 5072
       singleResponseResourcesMatchTypes: | 
                      {
                      "resourceTypes" : "*"
                      }

resourceProxyService:
  resourceFetcherEndpoints: http://rfprodeusaks.abc.prod.eusaks:6072

resourceProxyServiceAccount: 
# MI of idm partner
  clientId: 0d27a978-3ca2-4d6b-9fa6-031e2c34bfb0

cacheService:
  enabled: false

# Monitoring Information
monitorInfo:
  exporterType: GENEVA # default is console exporter
  isInternalPartner: true

genevaAccounts:
  datalabs:
    gcs_environment: DiagnosticsProd
    gcs_account: ARGDataLabs
    gcs_region: eastus
    gcs_namespace: ARGDataLabs
    gcs_config_version: "1.6"
    miResourceId: /subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourcegroups/MC_DataLabsidmRG-eastus_idmprodeusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/idmprodeusaks-agentpool
  partner:
    gcs_environment: DiagnosticsProd
    gcs_account: ARGIdMapping
    gcs_region: eastus
    gcs_namespace: ARGIdMapping
    gcs_config_version: "3.1"
    miResourceId: /subscriptions/9b776e32-83f7-4e98-b234-f43612dea78d/resourcegroups/MC_DataLabsidmRG-eastus_idmprodeusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/idmprodeusaks-agentpool

mdm:
  # Leave metric_endpoint commented out for PROD environment. Uncomment it for INT environment.
  # metricEndpoint: https://global.ppe.microsoftmetrics.com/

  accountInfo:
    DataLabs:
      account: ARGDataLabs
      namespace: ARGDataLabs
    Partner: 
      account: ARGIdMapping
      namespace: ARGIdMapping

  # objectId of idm aks-agentpool MI (kubelet identity)
  configData: >
    {
      "imdsInfo": [
        {
          "account": "ARGDataLabs",
          "objectId": "f2305251-f026-408b-bf60-bdbc6784bde9"
        },
        {
          "account": "ARGIdMapping", 
          "objectId": "f2305251-f026-408b-bf60-bdbc6784bde9"
        }
      ]
    }

keyVault:
  name: idmprodeuskv
  clientId: 87daea53-4435-4172-81bc-3459865ff6a4

adminService:
  isEnabled: true
  sslSecretProvider:
    certificateName: idmprodeusaks-ssl

adminServiceConfigMap:
  dstsRealm: realm://dsts.core.windows.net/
  dstsName: prod-dsts.dsts.core.windows.net
  serviceDns: prod.datalabs.core.windows.net
  allowedActors: GenevaActionsPublicPrimary,GenevaActionsPublicSecondary,GenevaActionsPublicWestUs