# Values File for Resource Alias in prod eus Environment
primaryRegionName: "eus"
backupRegionName: "wu3"

solutionInfo:
  solutionName: &solutionName rassolution
  aksClusterName: rasprodeusaks
  environment: Prod
  region: eastus
  scaleUnit: *solutionName

ioService:
  replicaCount: 5 # override from dataLabServices.yaml

# use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
ioServiceAccount:
#MI of ras partner
  clientId: 908fde98-51a3-4584-96ff-6308559e9eee
  tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

ioConfigMap:
  inputEventHubNameSpaceAndName: "rasprodeuspipehns0/rasprodeuspipeh;rasprodeuspipehns1/rasprodeuspipeh"
  outputEventHubNameSpaceAndName: "rasprodeusopehns0/rasprodeusopeh;rasprodeusopehns1/rasprodeusopeh"
  eventHubStorageAccountName: "0rasprodeusehcpsa"
  blobStorageAccountNames: "" # No source of truth
  backupInputEventHubNameSpaceAndName: "rasprodeusbpipehns0/rasprodeusbpipeh/00:05:00;rasprodeusbpipehns1/rasprodeusbpipeh/00:05:00"
  backupBlobStorageAccountNames: ""
  serviceBusNameSpaceAndName: "rasprodeussb0/0rasprodeussbq;rasprodeussb1/1rasprodeussbq"
  outputDataset: "rassolution"
  useSourceOfTruth: "false"
  allowedOutputTypes: "microsoft.maintenance/scheduledevents;microsoft.aliases/namespaces/types/identifiers/values"
  arnPublishStorageAccountNames: "0rasprodeusarnpsa;1rasprodeusarnpsa;2rasprodeusarnpsa;3rasprodeusarnpsa;4rasprodeusarnpsa;5rasprodeusarnpsa"
  arnPublishEventGridDomainIds: "/subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourceGroups/DataLabsrasRG-eastus/providers/Microsoft.EventGrid/domains/rasprodeusapeg1;/subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourceGroups/DataLabsrasRG-eastus/providers/Microsoft.EventGrid/domains/rasprodeusapeg2"
  arnPublishEventGridDomainEndpoints: "https://rasprodeusapeg1.eastus-1.eventgrid.azure.net/api/events;https://rasprodeusapeg2.eastus-1.eventgrid.azure.net/api/events"
  arnPublishEventGridTopics: "/subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourceGroups/DataLabsrasRG-eastus/providers/Microsoft.EventGrid/domains/rasprodeusapeg1/topics/arnpublishtopic;/subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourceGroups/DataLabsrasRG-eastus/providers/Microsoft.EventGrid/domains/rasprodeusapeg2/topics/arnpublishtopic"
  pairedRegionArnPublishEventGridDomainIds: "/subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourceGroups/DataLabsrasRG-westus3/providers/Microsoft.EventGrid/domains/rasprodwu3apeg1;/subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourceGroups/DataLabsrasRG-westus3/providers/Microsoft.EventGrid/domains/rasprodwu3apeg2"
  pairedRegionArnPublishEventGridDomainEndpoints: "https://rasprodwu3apeg1.westus3-1.eventgrid.azure.net/api/events;https://rasprodwu3apeg2.westus3-1.eventgrid.azure.net/api/events"
  pairedRegionArnPublishEventGridTopics: "/subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourceGroups/DataLabsrasRG-westus3/providers/Microsoft.EventGrid/domains/rasprodwu3apeg1/topics/arnpublishtopic;/subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourceGroups/DataLabsrasRG-westus3/providers/Microsoft.EventGrid/domains/rasprodwu3apeg2/topics/arnpublishtopic"

partnerConfig:    
  pods:
  - name: ras-solution
    serviceName: ras-solution-service
    replicaCount: 5
    partnerConfigMap:
      name: ras-solution-config    
    containers:
     - name: raspartnersolution
       repository: datalabsprodacr.azurecr.io/raspartnersolution
       tag: [[<BUILD_VERSION>]]
       port: 5072
       singleResponseResourcesMatchTypes: | 
                      {
                      "resourceTypes" : "*"
                      }

resourceProxyService:
  resourceFetcherEndpoints: http://rfprodeusaks.ras.prod.eusaks:6072
  partnerCertificates:
    isEnabled: true
    tenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d
    aadAuthority: https://login.microsoftonline.com
    aadTokenIssuer: https://sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/
    qfdClient:
      endpoints: https://arg-prod-rp.arg.core.windows.net
      certificateName: datalabs-ras-dsts-client-prod-eastus-gov-rp-art
      dstsSkipServerCertificateValidation: false
      dstsClientId: 34465100-c575-4689-ac4d-2f884317624a
      dstsServerId: bce8590f-51bd-4560-b478-9cfb5aab0500
      dstsClientHome: "https://useast-passive-dsts.dsts.core.windows.net/dstsv2/7a433bfc-2514-4697-b467-e0933190487f"
      dstsServerHome: "https://prod-passive-dsts.dsts.core.windows.net/dstsv2/7a433bfc-2514-4697-b467-e0933190487f"
      dstsServerRealm: "realm://dsts.core.windows.net/7a433bfc-2514-4697-b467-e0933190487f/"

resourceProxyServiceAccount: 
# MI of ras partner
  clientId: 908fde98-51a3-4584-96ff-6308559e9eee

resourceProxyConfigMap:
  getIdMappingAllowedTypes:
    "*:qfd|2016-09-01"

# Monitoring Information
monitorInfo:
  exporterType: GENEVA # default is console exporter
  isInternalPartner: true

genevaAccounts:
  datalabs:
    gcs_environment: DiagnosticsProd
    gcs_account: ARGDataLabs
    gcs_region: eastus
    gcs_namespace: ARGDataLabs
    gcs_config_version: "1.6"
    miResourceId: /subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourcegroups/MC_DataLabsrasRG-eastus_rasprodeusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rasprodeusaks-agentpool
  partner:
    gcs_environment: DiagnosticsProd
    gcs_account: AliasDatalabsSlnProd
    gcs_region: eastus
    gcs_namespace: AliasDatalabsSlnProd
    gcs_config_version: "1.1"
    miResourceId: /subscriptions/8956daf3-20ca-419f-bb01-aab21c6a63f4/resourcegroups/MC_DataLabsrasRG-eastus_rasprodeusaks_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rasprodeusaks-agentpool

mdm:
  # Leave metric_endpoint commented out for PROD environment. Uncomment it for INT environment.
  # metricEndpoint: https://global.ppe.microsoftmetrics.com/

  accountInfo:
    DataLabs:
      account: ARGDataLabs
      namespace: ARGDataLabs
    Partner: 
      account: AliasDatalabsSlnProd
      namespace: AliasDatalabsSlnProd

  # objectId of idm aks-agentpool MI (kubelet identity)
  configData: >
    {
      "imdsInfo": [
        {
          "account": "ARGDataLabs",
          "objectId": "ce724c06-04c0-42a3-9de7-ead3dbc6d4fb"
        },
        {
          "account": "AliasDatalabsSlnProd", 
          "objectId": "ce724c06-04c0-42a3-9de7-ead3dbc6d4fb"
        }
      ]
    }

keyVault:
  name: rasprodeuskv
  clientId: 2dc35cac-1f74-463a-86e0-204dc4aef028

adminService:
  isEnabled: true
  sslSecretProvider:
    certificateName: rasprodeusaks-ssl

adminServiceConfigMap:
  dstsRealm: realm://dsts.core.windows.net/
  dstsName: prod-dsts.dsts.core.windows.net
  serviceDns: prod.datalabs.core.windows.net
  allowedActors: GenevaActionsPublicPrimary,GenevaActionsPublicSecondary,GenevaActionsPublicWestUs