apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
    azure.workload.identity/client-id: {{ .Values.ioServiceAccount.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.ioServiceAccount.tenantId }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ .Values.ioServiceAccount.name }}
  namespace: {{ .Values.solutionNameSpace }}
---
{{- if .Values.resourceProxyService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
    azure.workload.identity/client-id: {{ .Values.resourceProxyServiceAccount.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.resourceProxyServiceAccount.tenantId }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ .Values.resourceProxyServiceAccount.name }}
  namespace: {{ .Values.solutionNameSpace }}
{{- end }}
