apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # use cmd `az identity show --resource-group "${RESOURCE_GROUP}" --name "${MI_NAME}" --query 'clientId' -otsv` to get the client-id of the MI
    azure.workload.identity/client-id: {{ .Values.resourceFetcherServiceAccount.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.resourceFetcherServiceAccount.tenantId }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ .Values.resourceFetcherServiceAccount.name }}
  namespace: {{ .Values.resourceFetcherNameSpace }}
