{{- if .Values.adminService.isEnabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.adminService.sslSecretProvider.className }}
  namespace: {{ .Values.adminServiceNameSpace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.keyVault.clientId }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.adminService.sslSecretProvider.certificateName | quote }}
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
{{- end }}