{{- if .Values.adminService.isEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.adminService.serviceAccount.role }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "services", "pods/log"]
  verbs: ["get", "patch", "update", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale", "daemonsets", "statefulsets"]
  verbs: ["get", "patch", "update", "list", "create"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers", "horizontalpodautoscalers/status"]
  verbs: ["get", "patch", "update", "list", "create"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.adminService.serviceAccount.rolebinding }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.adminService.serviceAccount.name }}
  namespace: {{ .Values.adminServiceNameSpace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Values.adminService.serviceAccount.role }}
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.adminService.serviceAccount.name }}
  namespace: {{ .Values.adminServiceNameSpace }}
{{- end }}